name       : lazarus
version    : 1.6.2
release    : 2
source     :
    - https://pilotfiber.dl.sourceforge.net/project/lazarus/Lazarus%20Zip%20_%20GZip/Lazarus%201.6.2/lazarus-1.6.2-0.tar.gz : eae73ac1d50456d191e13601ea5c333a8816732f6fcd0b849c3685da869cc1ef
license    :
    - GPL-2.0
    - LGPL-2.1
    - MPL-1.0
component  : programming.tools
summary    : Lazarus is a Rapid Application Development Tool for Free Pascal.
description: |
    Lazarus is a Rapid Application Development Tool for Free Pascal.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - fpc
rundeps    :
    - fpc
setup      : |
    sed -i "s|/usr/local|$installdir/usr|g" Makefile
build      : |
    %make -j1
install    : |
    %make_install
