name       : lazarus
version    : 1.6.4
release    : 3
source     :
    - https://sourceforge.net/projects/lazarus/files/Lazarus%20Zip%20_%20GZip/Lazarus%201.6.4/lazarus-1.6.4-0.tar.gz/download : 336654c5ad32244e64a56511108965b6b8eb25fe5882f61b2c15a24d8435a5e2
license    :
    - GPL-2.0
    - LGPL-2.1
    - MPL-1.0
component  : programming.tools
summary    : Lazarus is a Rapid Application Development Tool for Free Pascal.
description: |
    Lazarus is a Rapid Application Development Tool for Free Pascal.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - fpc
rundeps    :
    - fpc
    - gdb
setup      : |
    sed -i "s|/usr/local|$installdir/usr|g" Makefile
build      : |
    %make -j1
install    : |
    %make_install
    install -Dm 00644 $pkgfiles/lazarus.desktop $installdir/usr/share/applications/lazarus.desktop