name       : lazarus
version    : 2.0.2
release    : 8
source     :
    - ftp://ftp.freepascal.org/pub/lazarus/releases/Lazarus%20Zip%20_%20GZip/Lazarus%202.0.2/lazarus-2.0.2.tar.gz : e9d07f176e63c6ff7cf693a135ee66135c147ba398f67b8c6fe892c726f6a476
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : programming.tools
summary    : Lazarus is a Rapid Application Development Tool for Free Pascal
description: |
    Lazarus is a Rapid Application Development Tool for Free Pascal.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - fpc-src
rundeps    :
    - fpc-src
    - gdb
    - make
setup      : |
    # do some cleanup
    rm -rf debian
    pushd tools
        find install -depth -type d ! \( -path "install/linux/*" -o -path "install/linux" -o -path "install" \) -exec rm -rf '{}' \;
    popd
build      : |
    export FPCDIR=/usr/share/fpc/src

    fpcmake -Tall
    pushd components
        fpcmake -Tall
    popd

    make bigide OPT='-gl -gw'
    make tools OPT='-gl -gw'
install    : |
    %make_install INSTALL_PREFIX=$installdir/usr
