name       : lazarus
version    : 2.0.12
release    : 13
source     :
    - https://downloads.sourceforge.net/project/lazarus/Lazarus%20Zip%20_%20GZip/Lazarus%202.0.12/lazarus-2.0.12.tar.gz : ba6cef7f823a2d28166229982efc926039d42313c40e22fe0c6776c13d0015b2
homepage   : https://www.lazarus-ide.org
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
summary    :
    - Lazarus is a Rapid Application Development Tool for Free Pascal
    - ^qt5pas : Free Pascal Qt5 binding library
description:
    - Lazarus is a Rapid Application Development Tool for Free Pascal.
    - ^qt5pas : Free Pascal Qt5 binding library.
component  :
    - programming.tools
    - ^qt5pas : programming.library
    - ^qt5pas-devel : programming.devel
patterns   :
    - ^qt5pas : /usr/lib64/libQt5Pas.so*
    - ^qt5pas-devel : /usr/lib64/libQt5Pas.so
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(gtk+-2.0)
    - fpc-src
rundeps    :
    - fpc-src
    - gdb
    - make
setup      : |
    # Remove non-Linux and distro-specific files.
    rm -rf debian
    find tools/install -mindepth 1 -maxdepth 1 -type d -not -name linux -exec rm -rf {} +
build      : |
    export FPCDIR=/usr/share/fpc/src

    fpcmake -Tall
    pushd components
        fpcmake -Tall
    popd
    make bigide OPT='-gl -gw'
    make tools OPT='-gl -gw'

    # Build Qt5Pas.
    pushd lcl/interfaces/qt5/cbindings
        %qmake
        %make
    popd
install    : |
    %make_install INSTALL_PREFIX=$installdir/usr

    # Install Qt5Pas.
    %make_install -C lcl/interfaces/qt5/cbindings INSTALL_ROOT=$installdir
    pushd $installdir/usr/share/lazarus/lcl/interfaces/qt5/cbindings
        for f in libQt5Pas.so*; do
            ln -sf %libdir%/$f $f
        done
        rm -rf tmp
    popd

    # Cleanup.
    find $installdir -type d -empty -delete
    find $installdir -depth -type d -name '*.app' -prune -exec rm -rf {} +
    rm -rf $installdir/usr/share/lazarus/tools/install
