name       : lazarus
version    : 1.8.2
release    : 5
source     :
    - ftp://ftp.freepascal.org/pub/lazarus/releases/Lazarus%20Zip%20_%20GZip/Lazarus%201.8.2/lazarus-1.8.2.tar.gz : 252861f86b7e49487fa925195b78e8ab6a68528d3e6059cf68630fb5bc6d5219
license    :
    - GPL-2.0
    - LGPL-2.1
    - MPL-1.0
component  : programming.tools
summary    : Lazarus is a Rapid Application Development Tool for Free Pascal
description: |
    Lazarus is a Rapid Application Development Tool for Free Pascal.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - fpc-src
rundeps    :
    - fpc-src
    - gdb
    - make
setup      : |
    %patch -p1 < $pkgfiles/0001-patch-desktop-file.patch

    # do some cleanup
    rm -rf debian
    pushd tools
        find install -depth -type d ! \( -path "install/linux/*" -o -path "install/linux" -o -path "install" \) -exec rm -rf '{}' \;
    popd
build      : |
    export FPCDIR=/usr/share/fpc/src

    fpcmake -Tall
    pushd components
        fpcmake -Tall
    popd

    make bigide OPT='-gl -gw'
    make tools OPT='-gl -gw'
install    : |
    %make_install INSTALL_PREFIX=$installdir/usr
